import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header, ProfileCard } from "@/components/common";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-100 text-gray-600 dark:bg-black dark:text-gray-400">
        {/*<Header /> */}
        <div className="max-w-screen-xl px-4 lg:px-8 mx-auto pt-16 lg:pt-24">
          <div className="grid grid-cols-1 lg:grid-cols-9 gap-4 xl:gap-x-8">
            <div className="lg:col-span-3">
              <ProfileCard />
            </div>
            <div className="lg:col-span-6">
              <div className="bg-white p-3 lg:p-4 xl:p-6 rounded-2xl">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
