"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@/app/components/common";

import Sidebar from "@/app/components/common/Sidebar/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-100 text-slate-950 dark:bg-slate-800 dark:text-slate-100">
        <Header />
        {children}
      </body>
    </html>
  );
}
